/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardContent: typeof import('./components/ui/CardContent.vue')['default']
    CardHeader: typeof import('./components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/CardTitle.vue')['default']
    ChatRoom: typeof import('./components/ChatRoom.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
  }
}
